### ISSUE TITLE
Choose existing disk as a boot disk on instance create

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/console#1060]
... but I should be able to, right?

Steps to repro:

- Create an instance, use an existing image as the disk of choice (I used debian, you can use whatever)
- Observe the disk and instance exist
- Stop the instance, delete it
- Observe the boot disk still exists
- Try to create a new instance using the old boot disk
- Observe that "boot disk" requires one of "{distros, images, snapshots}". Old boot disks do not show up here. Notably it can be attached as an "additional disk", but not as an old boot disk.

**Comment by david-crespo** [comment]
The problem here is we always insert a created disk from the "boot disk" section as the first element in the list of disks. I think in order to solve this properly we need to rework these two sections so that we are not introducing an artificial concept of boot disk. We do have that concept in the API in that the first disk in the list is treated as the boot disk, but there is otherwise nothing special about it. The Boot Disk section of the form is a helper to make clear that you almost certainly want at least one disk attached to your instance so you can boot from it.

Maybe we can keep the boot disk section but add a kind of toggle that lets you choose between creating a new disk and attaching an existing one. The thing I don't like about that is that it duplicates the distinction we already make under additional disks between create and attach. Maybe that's fine.

https://github.com/oxidecomputer/console/blob/046928022a7cb1fa7152819d6883155609ad4726/app/forms/instance-create.tsx#L196-L212

<img width="616" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/e78de81b-176b-418f-b8fc-18cdebc13cc6">

**Comment by benjaminleonard** [comment]
I only occasionally suggest the most convoluted solution
