### ISSUE TITLE
Add NIC to instance: validation problems with IP address field

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#1438]
Two issues here:
1. When adding a network interface to an existing instance, user can simply specify the VPC and subnet without a specific IP address. However, the address k/v pair is still passed to the API call with an empty value, resulting in an unhandled 400 error (i.e. the operation failed silently and the popup remains open).
2. If an IP address is specified but is invalid (e.g. outside of the subnet range), the Nexus validation error is also unhandled.

**Comment by augustuswm** [comment]
Ran into this just now. Looking at Nexus it looks like it is intentional that the ip address is optional. I think the bug here is the the console is sending an empty string value when it should be omitting it.

![image](https://github.com/oxidecomputer/console/assets/1377730/a4428218-88be-4b9e-bf09-e55605f77995)

The request sent on submission looks like:

```json
{"name":"net0","description":"","ip":"","subnet_name":"default","vpc_name":"default"}
```
and the response is:
```json
{
  "request_id": "6f39a0ab-a4eb-4904-bc42-9b1e8911e9e2",
  "message": "unable to parse JSON body: ip: invalid IP address syntax at line 1 column 39"
}
```

**Comment by david-crespo** [comment]
This wasn't fully completely by #1811.

**Comment by david-crespo** [comment]
I wasn't sure, so I confirmed on colo that issue 2 is not a problem anymore.

https://github.com/oxidecomputer/console/assets/3612203/6b7ca960-1e9d-4bce-a20e-efa52fada625
