### ISSUE TITLE
Instance create: fetch more disks and use comboboxes instead of listboxes

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/console#1837]
In instance create, the drop down selection for `Additional disks` -> `ATTACH EXISTING DISK" menu
only shows me about 100 disks.

I've created some 1400 disks, and I can't choose the disk I want as it is not showing up.
There should be some way to either show all the disks, or enter a few letters and have the set of 
choices filtered to match what I entered, or.. something else ??

<img width="1037" alt="DiskInstance" src="https://github.com/oxidecomputer/console/assets/9903989/b0774be5-ba0f-45ef-bd49-6920a43c141a">

**Comment by david-crespo** [comment]
100 is right — we're not specifying a page size and [the default in Dropshot is 100](https://github.com/oxidecomputer/dropshot/blob/164f2edc83189d93068c557fe8293d4c0c619526/dropshot/src/server.rs#L129), and Nexus is not overriding that default. "about" is also right because we're fetching those 100 and then filtering out already-attached disks client-side:

https://github.com/oxidecomputer/console/blob/a0bf47aaa5e4b431050af486f18d6d5382c82f60/app/forms/disk-attach.tsx#L39-L42

The simple thing to do is bump the page size to something really big and make it a combobox so you can search for the thing you want (ctrl-f works ok too). The highest Dropshot will go by default is 10,000. With 36 disks in a project on rack3, the response was 15 kB. `15 * 1000 / 36  = ~400 kB`. That seems fine, and we could go higher (which would be necessary if you're working with 1400). Here it is with 2000 disks in the picker. It's fine? It takes a second to open, but scrolls and ctrl-fs just fine.

https://console-git-its-2000-disks-oxidecomputer.vercel.app/projects/mock-project/instances-new

I also went on dogfood to check how long Nexus would take to return all 1485 of your images: 500ms (see timestamps on the left). Not bad! 

<img width="663" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/21b7b13e-6dec-49c2-bbb1-a4cca3d018e8">

More broadly, the real way to solve this is, as you suggest, some kind of server-side search based on what you type in. We don't have that capability in Nexus (see the ancient https://github.com/oxidecomputer/omicron/issues/507), which is why we sometimes get up to client-side hijinks as a workaround. We talk about this problem a lot within product eng and see it as a major project for the next 6 months.

In the meantime, my experiments above suggests there is no problem with bumping up the page size to something absurd.

**Comment by benjaminleonard** [comment]
We're using radix for the dropdown and there's some real issues with that library and performance at the moment.

**Comment by david-crespo** [comment]
The listbox is actually headless-ui `Select`. Same deal though. I'd be surprised if we really need virtualization (all oxide backend devs ignore this word) for 2000 simple elements but it's possible.

**Comment by benjaminleonard** [comment]
Should have known that, having built it...

**Comment by charliepark** [comment]
Looks like the best path forward will involve using Headless UI's combobox with a large number of items fetched, and using list virtualization
https://tailwindcss.com/blog/headless-ui-v2#combobox-list-virtualization

**Comment by charliepark** [comment]
Possibly will be partially fixed by #1942

**Comment by david-crespo** [comment]
This is like 90% fixed. We now fetch 1000 disks 

https://github.com/oxidecomputer/console/blob/49d6d7d81f14ed5c258af6ccba1251c62fefeb68/app/forms/instance-create.tsx#L152-L162

And the attach side modal form uses a combobox:

https://github.com/oxidecomputer/console/blob/9c532ce9eea74f5ad7a8511716da14d3ea93b248/app/forms/disk-attach.tsx?plain=1#L59-L66

However, we're still using a listbox for the existing disk picker for the boot disk (and the image pickers). I wanted to let the combobox stew a bit before putting it in this super key flow. Now we should just go for it.

https://github.com/oxidecomputer/console/blob/49d6d7d81f14ed5c258af6ccba1251c62fefeb68/app/forms/instance-create.tsx#L540-L560
