### ISSUE TITLE
Disable firewall rule form submission when certain inputs (target, host filter, port filter) have been updated but not "added"

### ISSUE THREAD

**Issue by charliepark** [oxidecomputer/console#2068]
The situation: A user, new to the console, created a port filter as part of a firewall rule. They didn't `Add` that port filter as a part of their flow, and assumed that the port filter was created when they created the overall firewall rule. Being new to console, they didn't know what to look for on the list of firewall rules to see that the port filter was missing.

The idea with this issue, then, is to disable the overall form if certain inputs (target, host filter, port filter) have been modified but not "committed" (by clicking the "add target/filter" button).

I'm open to input / feedback on this, if people have opinions. Ultimately, the goal is to make sure that half-completed steps aren't misunderstood to be completed steps, so other solutions / ideas are welcome as well.

(Note that this is different from the earlier bug where hitting "enter" when in the port filter input submitted the overall form.)

**Comment by benjaminleonard** [comment]
Is there a validation here which might catch this – like a firewall should have at least a target or filter? At which point the user will realise they haven't been added.

**Comment by david-crespo** [comment]
I am skeptical of validating more strictly as we want these to be quite free-form, and I think it's reasonable to let someone make a rule with no filters, and then add the filters later. I do think there is a real problem here, but to me it's better solved through better visual representation of the filters on a rule. Right now we just have a "filters" column. When there aren't any port filters, you can't even tell that's a thing. When there is a port filter, we don't even say the word "port". The form not very dense at all and it's very cramped in the side modal, so it's impossible to get a bird's-eye view of what the capabilities are, what is the overall structure of a firewall rule. You can see all the filters at once here, but there is so much space and so little structure to it — to me it conveys very little about what's going on.

<img width="504" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/1856621b-0d9b-4fe2-b6b4-382d1314070d">

**Comment by david-crespo** [comment]
As I elaborated here, I don't think this idea works, or at least making it work is too complicated to be worth it.

https://github.com/oxidecomputer/console/pull/2190#issuecomment-2075473403

**Comment by charliepark** [comment]
Per David's comment above, closing this one
