### ISSUE TITLE
Instance quick actions need feedback and confirmation (or remove them)

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2276]
On instance detail, we put instance actions like stop/start/delete etc in the quick actions menu, but when I tried these I noticed several problems:

* No toast feedback or query invalidate on success
* Seemed not to work sometimes
* No confirmation on destructive actions

I would guess roughly no one is using these anyway, so it could well be the most expedient fix is to remove them from the menu, and then we can put them back in later if we have time.

https://github.com/oxidecomputer/console/blob/e7d7d95d02e4c4b251a4431b5f75849d8720db2c/app/pages/project/instances/instance/InstancePage.tsx#L119-L142

**Comment by charliepark** [comment]
A few notes on this
- I find the actions on the per-instance page to be kind of useful, rather than using the actions on the index / list of instances page. It's quite possible my typical usage is different from a normal usage pattern, but I wonder if removing the actions is best.
- I think I'm seeing confirmation on the dangerous actions; maybe I'm looking at the wrong thing?
- I think some of our e2e tests use the instance page actions as part of their flow, so we might need to re-think how we want to handle those.

**Comment by david-crespo** [comment]
You are looking at the wrong thing: what I call "quick actions" is the cmd+k modal UI.

**Comment by charliepark** [comment]
I wondered if that might be the case. 🫠
