### ISSUE TITLE
Add more actions menu on IP pool detail that lets you edit

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2353]
Right now you can only edit from the list view. Check other resources with a detail view to see if we need to make this change, like VPC and instance.

**Comment by charliepark** [comment]
Do we want to continue to allow editing from the list view? If so, we'll need to think about the URL scheme we'll want to use.

Currently, when editing from the list view (http://localhost:4000/system/networking/ip-pools), clicking on the `Edit` action in the table loads up http://localhost:4000/system/networking/ip-pools/ip-pool-2/edit, and drops the side-modal form on that page.
<img width="1290" alt="Screenshot 2024-08-29 at 3 35 00 PM" src="https://github.com/user-attachments/assets/ce77ed85-1b14-489b-acd8-1ddf076495c9">

Clicking through from the table to the resource page gives you http://localhost:4000/system/networking/ip-pools/ip-pool-2, but with no current means of editing the resource from that page.
<img width="1287" alt="Screenshot 2024-08-29 at 3 43 13 PM" src="https://github.com/user-attachments/assets/35448d32-f954-4d92-bc34-bb744efcfffa">

I think it would make sense to move the side modal to the IpPoolPage directly. When loading [the /edit page](http://localhost:4000/system/networking/ip-pools/ip-pool-2/edit), the user would have the IP Pool 2 resource page, rather than the list page, in the background. If we make that move, though, and if we want to maintain the editing functionality on the root list page, we'll need to figure out a new URL pattern for that view. I'm inclined to say that we should just move the URL and editing to the resource page and remove "Edit" from the action menu on each row of the list page. As always, open to alternate opinions.
