### ISSUE TITLE
Uploading a TLS certificate should be mandatory during silo creation

### ISSUE THREAD

**Issue by wfchandler** [oxidecomputer/console#2578]
Currently the console does not require a TLS certificate to be uploaded during the silo creation workflow.

This is a mandatory field in the API and failure to provide a cert may leave the newly created silo broken in unpredictable ways.

**Comment by twinfees** [comment]
For additional context, created a test silo without a TLS certificate. Running a `curl -v` against that silo resulted in a `tlsv1 alert access denied` error.

**Comment by augustuswm** [comment]
Similar to the "soft-failures" we have on image import, we could probably decode the certificate and verify that either the the CN or SAN  covers the computed silo url `{silo}.sys.{domain}`

**Comment by david-crespo** [comment]
I was wondering how we could fail to require it if it’s a required field, but I think it’s because it’s a required array that is allowed to be empty.

https://docs.oxide.computer/api/silo_create

**Comment by benjaminleonard** [comment]
We should also make sure this requirement is included in the API docs – a note in the description is probably sufficient. I don't see a way of setting `minItems` in the OpenAPI schema directly through the type. It looks like the only `minItems` we have there currently are arrays of fixed size, with min and max set to that length.

@ahl Have you considered any way in which we might be add some validation to the API that progenitor cannot discern from the type directly? Might also come in useful for cases where's there's a defined limit, e.g. max instance CPUs. In this utopian world we could use that instead of hard coded values for client-side validation.
