### ISSUE TITLE
[Instance create] `user_data` textarea/file input

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#800]
[Discussed in chat](https://matrix.to/#/!YNYPOVxjAUeXksTcRj:oxide.computer/$U3fCENcgUYFVwnXh3zyy39m6YF2D1kMbC612uFnNFVE?via=oxide.computer&via=unix.house&via=timecube.club). This is not fully fleshed out, but it's [in the API](https://github.com/oxidecomputer/omicron/pull/911). `user_data` is an optional string field on the instance create POST. The easy version is a text area you can paste into. The fancy version would also allow a file upload. This is sort of an advanced feature on instance create, so we would probably want to hide it in a collapsed section.

**Comment by david-crespo** [comment]
We do have the drag and drop file component now, so this would be very easy.

**Comment by benjaminleonard** [comment]
@askfongjojo @iliana @zephraph @david-crespo 

Quick pass at this – we're getting to the point where any additions to the instance create add a little clutter and a bit of friction. I'm proposing that we add an "Advanced" section (open to alternative names) that contains an accordion of lesser used inputs. Perhaps we more networking in here since more often than not a user just leaves it at default, and we include the user data file upload there too.

Including both text area and file upload or some hybrid would be a nice touch, but we already have the file upload which makes easy to add and I'm assuming most people's workflows.

<img width="1335" alt="image" src="https://github.com/oxidecomputer/console/assets/4020798/08e2f149-3f60-4073-bfb2-4467cbcb9475">

If you're happy with that as an approach I could probably squeeze in a PR ahead of the next releaase.

**Comment by askfongjojo** [comment]
@benjaminleonard - Your proposal sounds good to me.

**Comment by david-crespo** [comment]
I like it too.
